services:
  - type: web
    name: 3d-chess-premium
    runtime: node
    rootDir: server
    repo: https://github.com/ssdevstudio/3d-chess-premium
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: HOST
        value: https://threed-chess-premium.onrender.com
      - key: FRONTEND_URL
        value: https://ssdevstudio.github.io/Chess-Game/chess.html
